apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spower-data
  namespace: spower
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 20Gi
