apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: spower
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: minhdtb/spower-api:latest
          name: api
          ports:
            - containerPort: 8090
          volumeMounts:
            - mountPath: /pb_data
              name: spower-data
      volumes:
        - name: spower-data
          persistentVolumeClaim:
            claimName: spower-data

