apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless
  namespace: spower
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: headless
  template:
    metadata:
      labels:
        app: headless
    spec:
      containers:
        - image: ghcr.io/go-rod/rod
          name: headless
          ports:
            - containerPort: 7317
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
