namePrefix: spower-
resources:
- headless-deployment.yaml
- headless-service.yaml
- api-pvc.yaml
- api-deployment.yaml
- api-service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: minhdtb/spower-api
  newTag: 670f512d7d6da00f432a5b365def980d0e3d9570
