namePrefix: spower-
resources:
- headless-deployment.yaml
- headless-service.yaml
- api-pvc.yaml
- api-deployment.yaml
- api-service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: minhdtb/spower-api
  newTag: 583576d68349eefbaae38bd0c6d730ba93dd21e2
